# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:  
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.203
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Unit Tests
      run: dotnet test tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report      
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment      
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
    - name: Run Selenium Tests
      if: success() || failure()
      run: dotnet test examples/Mafin.Web.UI.Selenium.Example/Mafin.Web.UI.Selenium.Example.csproj --configuration Release --no-build
      
    - name: Run Selenium Yapoml Tests
      if: success() || failure()
      run: dotnet test examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Web.UI.Selenium.YapomlExample.csproj --configuration Release --no-build
        
    - name: Pack
      if: success() || failure()
      run: dotnet pack --configuration Release --output artifact/
      
    - name: Git Version
      if: success() || failure()
      uses: codacy/git-version@2.4.0
      
    - name: Upload Pack Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3.1.2
      with:    
        name: uiframeworkpack:${{steps.version.outputs.version}}
        path: artifact/**
        if-no-files-foud: error
        retention-days: 30
      
