# This workflow will build, test and publish nuget package with actual version
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release and Publish flow

on:  
  workflow_dispatch: 
  push:
    branches: [ "main" ]

env:
  PACKAGE_OUPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.203
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Unit Tests
      run: dotnet test tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj --configuration Release --no-build --verbosity normal    

    - name: Git Version
      if: success() || failure()
      id: version
      uses: codacy/git-version@2.4.0      
      with:
        release-branch: main

    - name: Pack      
      run: dotnet pack --configuration Release --no-restore --no-build -p:PackageVersion=${{ steps.version.otputs.version-without-v }} --include-symbols --output ${{ env.PACKAGE_OUPUT_DIRECTORY }}

    - name: Push
      run: dotnet nuget push ${{ env.PACKAGE_OUPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.AUTH_TOKEN }} --skip-duplicate -s https://nuget.pkg.github.com/MAFIN-Squad/index.json
